# Hibernate config (your DB stuff)
spring.application.name=inventoryService
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
mp.messaging.incoming.products.enabled=false

quarkus.kafka.devservices.enabled=false
kafka.enabled = false
