quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:1970}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}

# Hibernate ORM: generate and execute tables in the database
quarkus.hibernate-orm.scripts.generation=drop-and-create
quarkus.hibernate-orm.scripts.generation.drop-target=database
quarkus.hibernate-orm.scripts.generation.create-target=database
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# products configuration
mp.messaging.incoming.products.connector=smallrye-kafka
mp.messaging.incoming.products.topic=inventory-topic
mp.messaging.incoming.products.bootstrap.servers=kafka-0.kafka:9092
mp.messaging.incoming.products.group.id=my-group
mp.messaging.incoming.products.value.deserializer=org.example.jsonb.UpdateQuantityDeserializer
mp.messaging.incoming.products.value.deserializer.type=org.example.dto.Event

mp.messaging.outgoing.products-out.connector=smallrye-kafka
mp.messaging.outgoing.products-out.topic=inventory-topic
mp.messaging.outgoing.products-out.bootstrap.servers=kafka-0.kafka:9092
mp.messaging.outgoing.products-out.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer

#